# This action is centrally managed in https://github.com/stiggio/.github/
# Don't make changes to this file in this repo as they will be overwritten with changes made to the same file in above mentioned repo

name: Tag release and write changelog
on:
  push:
    branches: [ master ]


jobs:
  tag-changelog:
    ## avoid running when our service user is committing changelog to master. also don't trigger on the centrally managed.
    if: github.actor != 'cicdstigg' && github.repository != 'stiggio/.github'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GUTHUB_SERVICE_TOKEN }}

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/master/protection
          repository: ${{ github.repository }}
          required_status_checks: |
            null
          required_pull_request_reviews: |
            null
          enforce_admins: |
            null
          restrictions: |
            null 
        env:
          GITHUB_TOKEN: ${{ secrets.GUTHUB_SERVICE_TOKEN }}

      - name: Conventional Changelog Action
        id: change_log_create
        uses: TriPSs/conventional-changelog-action@v3
        with:
          tag-prefix: ""
          git-user-name: ${{ github.event.pusher.name }}
          github-token: ${{ github.GUTHUB_SERVICE_TOKEN }}
          git-user-email: ${{ github.event.pusher.email }}

      - name: Branch protection ON
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/master/protection
          repository: ${{ github.repository }}
          required_status_checks: |
            strict: true
            contexts:
              - run-tests
          required_pull_request_reviews: |
            dismiss_stale_reviews: false
            required_approving_review_count: 1
          restrictions: |
            null 
          enforce_admins: |
            true
        env:
          GITHUB_TOKEN: ${{ secrets.GUTHUB_SERVICE_TOKEN }}
        
      - name: Get current PR
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: current_pr
      
      # Step is used to get branch name
      - name: Curl to get pr metadata
        run: |
           curl -H "Accept: application/vnd.github+json"  -H "Authorization: token ${{ secrets.GH_NPC_READ_TOKEN }}" https://api.github.com/repos/stiggio/${{ github.event.repository.name }}/pulls/${{ steps.current_pr.outputs.number }} > pr.json
      
      #  Extract branch name from curl output json
      - name: Get brach name
        id: branch_name
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'pr.json'
          prop_path: 'head.ref'
        
      - name: Dispach a trigger to the build
        uses: peter-evans/repository-dispatch@v1
        if: ${{ steps.change_log_create.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.GUTHUB_SERVICE_TOKEN }}
          event-type: tag-ready
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ steps.change_log_create.outputs.tag }}", "prLink": "${{ steps.current_pr.outputs.pr_url }}", "branchName": "${{steps.branch_name.outputs.prop}}", "pusherName": "${{ github.event.pusher.name }}", "pusherEmail": "${{ github.event.pusher.email }}"}'
